-- =============================================================================
-- Script   : ddl_gold.sql
-- Author   : Uzair Akhtar
-- GitHub   : https://github.com/HafizUzairAkhtar
-- =============================================================================
-- Purpose:
--     This script defines the view structure (DDL) for all three objects
--     in the 'gold' schema. These views represent the final, business-ready
--     layer of the Medallion Architecture — modeled as a Star Schema.
--
-- What Is a Star Schema?
--     A star schema organizes data into two types of objects:
--       - Dimension views  → Descriptive reference data (who, what, where)
--       - Fact views       → Transactional/measurable data (how many, how much)
--
-- Gold Layer Views:
--     gold.dim_customers   → Customer dimension (combines CRM + ERP data)
--     gold.dim_products    → Product dimension (combines CRM + ERP data)
--     gold.fact_sales      → Sales fact table (joins to both dimensions)
--
-- How Gold Differs from Silver:
--     Silver → Cleaned individual source tables, still separated by system
--     Gold   → Integrated, joined, and enriched views ready for analytics
--               - Surrogate keys added (customer_key, product_key)
--               - Business-friendly column names used
--               - Data from CRM and ERP merged into single unified views
--               - Only current/active records exposed (historical rows filtered)
--
-- What Is a Surrogate Key?
--     A surrogate key is a system-generated integer that uniquely identifies
--     each row in a dimension view. It is created using ROW_NUMBER() and has
--     no meaning in the real world — it exists only inside the data warehouse.
--     Surrogate keys are used instead of natural/source keys for joins in the
--     fact table because they are simpler, consistent, and decoupled from the
--     source systems.
--
-- Important Notes:
--     - Gold layer objects are VIEWS, not tables — they do not store data.
--     - Views are recreated fresh on every run of this script.
--     - No data load procedure is needed — views query silver layer on the fly.
--     - These views are the final output consumed by analysts and BI tools.
--
-- Execution Order:
--     Run this AFTER ddl_silver.sql and proc_load_silver.sql
--     (Silver tables must be populated before gold views can be queried)
-- =============================================================================


-- =============================================================================
-- Dimension View: gold.dim_customers
-- Source Tables : silver.crm_cust_info
--                 silver.erp_cust_az12   (LEFT JOIN — adds birthdate & gender)
--                 silver.erp_loc_a101    (LEFT JOIN — adds country)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- View: gold.dim_customers
-- Description: Unified customer dimension combining data from the CRM system
--              and two ERP tables. Each row represents one unique customer.
--
-- Key Design Decisions:
--     - customer_key  : Surrogate key generated by ROW_NUMBER() — used for
--                       joins in the fact table instead of the source cst_id.
--     - gender        : CRM is treated as the primary/trusted source.
--                       ERP gender is only used as a fallback when CRM = 'n/a'.
--     - Both ERP joins use LEFT JOIN to preserve all CRM customers even if
--       no matching ERP record exists for that customer.
-- -----------------------------------------------------------------------------
IF OBJECT_ID('gold.dim_customers', 'V') IS NOT NULL
    DROP VIEW gold.dim_customers;
GO

CREATE VIEW gold.dim_customers AS
SELECT
    ROW_NUMBER() OVER (ORDER BY ci.cst_id) AS customer_key,   -- Surrogate key for star schema joins
    ci.cst_id                              AS customer_id,     -- Original source ID from CRM
    ci.cst_key                             AS customer_number, -- Alphanumeric customer code from CRM
    ci.cst_firstname                       AS first_name,      -- Customer first name
    ci.cst_lastname                        AS last_name,       -- Customer last name
    la.cntry                               AS country,         -- Country from ERP location table
    ci.cst_marital_status                  AS marital_status,  -- Marital status (standardized in silver)
    CASE
        WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr            -- CRM is the primary source for gender
        ELSE COALESCE(ca.gen, 'n/a')                           -- Fallback to ERP if CRM has no gender
    END                                    AS gender,          -- Unified gender field
    ca.bdate                               AS birthdate,       -- Date of birth from ERP (not in CRM)
    ci.cst_create_date                     AS create_date      -- Date the customer was created in CRM
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca                              -- Adds birthdate and ERP gender
    ON ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la                               -- Adds country information
    ON ci.cst_key = la.cid;
GO


-- =============================================================================
-- Dimension View: gold.dim_products
-- Source Tables : silver.crm_prd_info
--                 silver.erp_px_cat_g1v2  (LEFT JOIN — adds category info)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- View: gold.dim_products
-- Description: Unified product dimension combining product details from the CRM
--              system with category and subcategory data from the ERP system.
--              Only currently active products are exposed — historical versions
--              of products (with a prd_end_dt) are excluded from this view.
--
-- Key Design Decisions:
--     - product_key   : Surrogate key generated by ROW_NUMBER() — ordered by
--                       start date and product key for consistency across loads.
--     - prd_end_dt filter: Products with a non-NULL end date are older/replaced
--                       versions. Filtering these out keeps the dimension clean
--                       and avoids duplicating products in reports.
--     - cat_id        : Derived column added in the silver layer (extracted from
--                       prd_key) — used here to join with the ERP category table.
-- -----------------------------------------------------------------------------
IF OBJECT_ID('gold.dim_products', 'V') IS NOT NULL
    DROP VIEW gold.dim_products;
GO

CREATE VIEW gold.dim_products AS
SELECT
    ROW_NUMBER() OVER (ORDER BY pn.prd_start_dt, pn.prd_key) AS product_key, -- Surrogate key for star schema joins
    pn.prd_id       AS product_id,     -- Original source ID from CRM
    pn.prd_key      AS product_number, -- Alphanumeric product code from CRM
    pn.prd_nm       AS product_name,   -- Product name
    pn.cat_id       AS category_id,    -- Derived category ID used to join ERP category table
    pc.cat          AS category,       -- Product category from ERP (e.g., Bikes, Components)
    pc.subcat       AS subcategory,    -- Product subcategory from ERP (e.g., Road Bikes, Helmets)
    pc.maintenance  AS maintenance,    -- Whether the product requires maintenance (Yes / No)
    pn.prd_cost     AS cost,           -- Product cost in whole currency units
    pn.prd_line     AS product_line,   -- Product line or series (e.g., Road, Mountain)
    pn.prd_start_dt AS start_date      -- Date the product version became active
FROM silver.crm_prd_info pn
LEFT JOIN silver.erp_px_cat_g1v2 pc                           -- Adds category and subcategory info
    ON pn.cat_id = pc.id
WHERE pn.prd_end_dt IS NULL;                                   -- Only expose current/active products
GO


-- =============================================================================
-- Fact View: gold.fact_sales
-- Source Tables : silver.crm_sales_details
--                 gold.dim_products   (LEFT JOIN — resolves product_key)
--                 gold.dim_customers  (LEFT JOIN — resolves customer_key)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- View: gold.fact_sales
-- Description: Central fact view containing all sales transactions.
--              Each row represents one line item in a sales order.
--              Links to both dimension views using their surrogate keys
--              (product_key and customer_key) instead of source system IDs.
--
-- Key Design Decisions:
--     - Surrogate keys (product_key, customer_key) are used instead of
--       natural keys (sls_prd_key, sls_cust_id) to align with star schema
--       best practices and ensure stable joins as source data evolves.
--     - Both dimension joins use LEFT JOIN to preserve all sales records,
--       even if a product or customer cannot be matched (e.g., data gaps).
--     - The three date columns (order, ship, due) are already clean DATE
--       types at this point — converted from raw integers in the silver layer.
--     - Measurable fields (sales_amount, quantity, price) satisfy the rule:
--       sales_amount = quantity × price (enforced during silver load).
-- -----------------------------------------------------------------------------
IF OBJECT_ID('gold.fact_sales', 'V') IS NOT NULL
    DROP VIEW gold.fact_sales;
GO

CREATE VIEW gold.fact_sales AS
SELECT
    sd.sls_ord_num  AS order_number,   -- Sales order number (e.g., SO54496)
    pr.product_key  AS product_key,    -- Surrogate key linking to gold.dim_products
    cu.customer_key AS customer_key,   -- Surrogate key linking to gold.dim_customers
    sd.sls_order_dt AS order_date,     -- Date the order was placed (cleaned DATE type)
    sd.sls_ship_dt  AS shipping_date,  -- Date the order was shipped (cleaned DATE type)
    sd.sls_due_dt   AS due_date,       -- Payment due date (cleaned DATE type)
    sd.sls_sales    AS sales_amount,   -- Total sales amount for the line item
    sd.sls_quantity AS quantity,       -- Number of units ordered
    sd.sls_price    AS price           -- Price per unit
FROM silver.crm_sales_details sd
LEFT JOIN gold.dim_products pr                                 -- Resolve product surrogate key
    ON sd.sls_prd_key = pr.product_number
LEFT JOIN gold.dim_customers cu                                -- Resolve customer surrogate key
    ON sd.sls_cust_id = cu.customer_id;
GO


-- =============================================================================
-- Gold layer view definitions complete.
-- 3 views created: 2 dimensions + 1 fact (Star Schema).
--
-- To query the gold layer:
--     SELECT * FROM gold.dim_customers;
--     SELECT * FROM gold.dim_products;
--     SELECT * FROM gold.fact_sales;
--
-- These views are ready for use in BI tools (Power BI, Tableau, etc.)
-- and can be queried directly for analytics and reporting.
-- =============================================================================